"""clear rule_id for Transaction when Rule gets deleted

Revision ID: 0c3dd6e569e6
Revises: 7ae2baed02f5
Create Date: 2021-01-23 19:31:52.899411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c3dd6e569e6'
down_revision = '7ae2baed02f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_rule', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_rule_id_ruleset'), 'ruleset', ['rule_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_rule_id_ruleset'), type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_rule', 'ruleset', ['rule_id'], ['id'])

    # ### end Alembic commands ###
