"""add start + end column to Ruleset

Revision ID: 766a0749e3c3
Revises: fc6a22ca4e5c
Create Date: 2022-08-03 09:45:20.147011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766a0749e3c3'
down_revision = 'fc6a22ca4e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruleset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ruleset_end'), ['end'], unique=False)
        batch_op.create_index(batch_op.f('ix_ruleset_start'), ['start'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruleset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ruleset_start'))
        batch_op.drop_index(batch_op.f('ix_ruleset_end'))
        batch_op.drop_column('end')
        batch_op.drop_column('start')

    # ### end Alembic commands ###
