"""delete constraint for Category

Revision ID: 7ae2baed02f5
Revises: 4e8905c33e99
Create Date: 2021-01-23 19:27:04.004208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae2baed02f5'
down_revision = '4e8905c33e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_parent_id_categories', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_categories_parent_id_categories'), 'categories', ['parent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_categories_parent_id_categories'), type_='foreignkey')
        batch_op.create_foreign_key('fk_categories_parent_id_categories', 'categories', ['parent_id'], ['id'])

    # ### end Alembic commands ###
