"""make Rule() name unique

Revision ID: c697cfd24629
Revises: 0c3dd6e569e6
Create Date: 2022-08-02 10:45:46.048016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c697cfd24629'
down_revision = '0c3dd6e569e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_ruleset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_ruleset',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('pattern', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=3), nullable=False),
    sa.Column('next_due', sa.DATE(), nullable=True),
    sa.Column('next_valuta', sa.FLOAT(), nullable=True),
    sa.Column('regular', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), server_default=sa.text("'1'"), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_ruleset_account_id_accounts', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_ruleset_category_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_ruleset'),
    sa.UniqueConstraint('name', name='uq_ruleset_name')
    )
    # ### end Alembic commands ###
