"""make Rule() name unique

Revision ID: fc6a22ca4e5c
Revises: 0c3dd6e569e6
Create Date: 2022-08-02 10:55:31.084973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc6a22ca4e5c'
down_revision = '0c3dd6e569e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruleset', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_ruleset_name'), ['name', 'account_id', 'type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruleset', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_ruleset_name'), type_='unique')

    # ### end Alembic commands ###
