"""add accounts table

Revision ID: 2f7b1d0b3c37
Revises: a2487f80fe2c
Create Date: 2020-02-02 22:43:11.745915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7b1d0b3c37'
down_revision = 'a2487f80fe2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('iban', sa.String(length=22), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key('fk_categories_account', 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('ruleset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key('fk_rules_account', 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), server_default='1', nullable=False))
        batch_op.create_foreign_key('fk_transactions_account', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_account', type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('ruleset', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rules_account', type_='foreignkey')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_account', type_='foreignkey')
        batch_op.drop_column('account_id')

    op.drop_table('accounts')
    # ### end Alembic commands ###
