"""use proper delete constraints for Account class

Revision ID: 51d6e928255f
Revises: 9d2f1a12d6eb
Create Date: 2021-01-10 15:47:25.306396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d6e928255f'
down_revision = '9d2f1a12d6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_account', type_='foreignkey')
        batch_op.create_foreign_key('fk_categories_account', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('ruleset', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rules_account', type_='foreignkey')
        batch_op.create_foreign_key('fk_rules_account', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_account', type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_rule', 'ruleset', ['rule_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_transactions_account', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_account', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_rule', type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_account', 'accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key(None, 'ruleset', ['rule_id'], ['id'])

    with op.batch_alter_table('ruleset', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rules_account', type_='foreignkey')
        batch_op.create_foreign_key('fk_rules_account', 'accounts', ['account_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('fk_categories_account', type_='foreignkey')
        batch_op.create_foreign_key('fk_categories_account', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###
