"""add color column to accounts table

Revision ID: a025f3a71951
Revises: 2f7b1d0b3c37
Create Date: 2020-03-22 20:22:31.918114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a025f3a71951'
down_revision = '2f7b1d0b3c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=6), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
