"""remove trend_calculated from transactions table

Revision ID: a2487f80fe2c
Revises: 07f9fee4d16a
Create Date: 2020-02-01 20:56:10.267930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2487f80fe2c'
down_revision = '07f9fee4d16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_rule_id'), ['rule_id'], unique=False)
        batch_op.drop_column('trend_calculated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trend_calculated', sa.BOOLEAN(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_transactions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))

    # ### end Alembic commands ###
